typedb/typedb-dependencies

- ci/sync_dependencies.py
- abstracted "replace dependency in cloned repo" action
- `WorkspaceDependencyReplacer` is responsible for replacing dependency in `dependencies/graknlabs/dependencies.bzl`
- `PackageJsonDependencyReplacer` is responsible for replacing dependency in `test/standalone/nodejs/package.json`
> Update dependency script so it supports client-nodejs => docs

- ci/sync_dependencies.py
- If you specify `repo_name` as `--source`, `$CIRCLE_SHA1` will be used as the last commit
Minor improvements
- `--dry-run` command line argument is not yet supported but is useful for testing. Add a `TODO` to implement it later.
- add a comment specifying why we need to call `grabl_credential()`
> Add ability to use commit ID from CircleCI in sync_dependencies script

- distribution/dependencies.bzl
Includes fixes from graknlabs/bazel-distribution#71
> Bump @graknlabs_bazel_distribution

- distribution/dependencies.bzl
Bump version to include changes in graknlabs/bazel-distribution#72
> Bump @graknlabs_bazel_distribution version

- deployment.properties
Added two brew taps: test tap and release tap
> deployment.properties - add deploy_brew configuration

- ci/release_approval.py
- ci/sync_dependencies.py
The `build-tools/ci` counterpart of https://github.com/graknlabs/grabl/pull/17
> Sign all requests to Grabl

- ci/BUILD
- ci/run-bazel-rbe.py
Fixes #30
Re-implementing `run-bazel-rbe` in Python
> run-bazel-rbe reimplementation in Python

- grpc/dependencies.bzl
Needed to use latest changes in proto compilation for Python generated files and reducing potential tech debt for further upgrade
> Upgrade @stackb_rules_proto to latest master

- distribution/maven/rules.bzl
- Run `distribution/maven/update.sh` to sync `rules.bzl`
> Sync Maven rules.bzl with latest @graknlabs_bazel_distribution

- checkstyle/config/checkstyle-file-header-agpl.txt
Update Grakn Core AGPL template, from 2018 to 2019.
> Update checkstyle - Grakn Core AGPL 2019

- .github/CODEOWNERS
We've added Ganesh and Max as code owners.
> Add Ganesh and Max as code owners

- dependencies/graknlabs/dependencies.bzl
- distribution/maven/rules.bzl
To include graknlabs/bazel-distribution#182
> Sync Maven rules with latest bazel-distribution

- checkstyle/config/checkstyle-file-header-agpl.txt
- checkstyle/config/checkstyle-file-header-grakn-kgms.txt
> Checkstyle: update copyright header to 2020

- distribution/maven/rules.bzl
Needed to include changes in graknlabs/bazel-distribution#219
> Sync Maven rules to latest bazel-distribution

- BUILD
- ci/rbe-image/Dockerfile
Upgrade image used in RBE builds
> Upgrade RBE Docker image

- WORKSPACE
- bazel/dependencies.bzl
Prepare to upgrade to Python across all of the stack
> Upgrade @rules_python to Python 3

- .circleci/config.yml
- ci/install-bazel-rbe.sh
Use Ubuntu 16.04 Image, and set the Python version based on the presence or absence of the RBE credential.
> Use new machine image in CI

- distribution/artifact/rules.bzl
We re-discovered a way of making the extract script a bazel executable rule.
> Change extract artifact to executable rule

- distribution/deps.bzl
Fix graknlabs/bazel-distribution#244
> Load @bazel_skylib together with bazel-distribution

- distribution/deps.bzl
- distribution/maven/rules.bzl
`dependencies` need to include fixes from graknlabs/bazel-distribution#245
> Sync Maven rules to latest version in @graknlabs_bazel_distribution

- dependencies/graknlabs/repositories.bzl
Bazel distribution bump dependencies for assemble-npm bug fix
> Bazel distribution bump dependencies for assemble-npm bug fix

- .github/PULL_REQUEST_TEMPLATE.md
- tool/checkstyle/rules.bzl
- tool/checkstyle/test-coverage.py
To make checkstyle more user-friendly
Add .DS_Store, LICENSE and .gitkeep to checkstyle exclusions
> Add .DS_Store, LICENSE and .gitkeep to checkstyle exclusions

- tool/terraform/install.sh
As Terraform is being used in more places, it makes sense to split installing it into a separate script
Script that installs Terraform
> Script to install Terraform

- library/maven/artifacts.bzl
We need to update the `jline` version to the newest for the new console to use the latest jline functionality.
> Update jline version

- library/maven/artifacts.bzl
We used the incorrect group id for jline3. Fix it with the correct group id.
See here https://github.com/jline/jline3#maven-usage
> Update jline group id

- distribution/deps.bzl
Upgrade `bazel-distribution` to include latest fixes to `assemble_pip`: graknlabs/bazel-distribution#275
Upgrade `bazel-distribution` to latest `master`
> Upgrade @graknlabs_bazel_distribution

- tool/misc/BUILD
- tool/misc/restart-repo-container.sh
- tool/misc/ssh-repo-container.sh
- tool/misc/ssh-repo-machine.sh
In order to simplify operations with `repo.grakn.ai` machine, we want to wrap them in Bazel targets.
Add scripts to SSH into the machine, Nexus container and restart the Nexus container
> Ease operations with repo.grakn.ai

- builder/python/deps.bzl
- distribution/deps.bzl
- tool/common/deps.bzl
Upgrade `rules-python` to `0.1.0` in order to speed up Client Python CI
Upgrade `@rules_python` to latest release, `@graknlabs_bazel_distribution` to latest `master` and adapt syntax accordingly
> Upgrade @rules_python

- distribution/artifact/BUILD
- distribution/artifact/artifact-repackage.sh
- distribution/artifact/rules.bzl
Implement a macro that would assist in building distributions that include Grakn Console.
Implement `artifact_repackage` macro
> Implement artifact_repackage

- tool/util/wait-for-host.kt
Make progress messages printed by `wait-for-host` more user-friendly and understandable.
Improve messages printed out by `wait-for-host`
> Improve progress messages in wait-for-host

- distribution/helm/deps.bzl
Deploy Helm package into our repo.
Add `distribution/helm/deps.bzl`
> Add dependencies for Helm

- library/maven/artifacts.bzl
Add Kubernetes client library to our Java dependencies
Depend on `io.kubernetes:client-java`, `io.kubernetes:client-java-api` and `io.kubernetes:client-java-util`
> Add Java client for Kubernetes API

- tool/release/docs.py
Generalise docs release script to work with other repositories.
- Parameterise and generalise docs release script to work with other repositories.
> Generalise docs release script to work with other repositories

- tool/release/docs.py
Fix adding submodule directory in doc release script.
Fix adding submodule directory in doc release script.
> Fix adding submodule directory in doc release script

- distribution/deployment.bzl
We added an `npm` private repo to `repo.vaticle.com`
> Add npm private repo

- library/maven/artifacts.bzl
We use the latest major version of google-guava.
Update guava from 23 to 30.1
> Update guava to version 30.1

- builder/rust/deps.bzl
Allow building Rust code across our repositories
Integrate `rules_rust` to be loadable in our repos
> Add rules_rust to allow building Rust code

- distribution/deps.bzl
Propogate a bugfix from vaticle/bazel-distribution#329
Bump `vaticle_bazel_distribution` to latest `master`
> Bump @vaticle_bazel_distribution

- distribution/deps.bzl
We upgraded to the latest bazel-distribution.
Upgrade bazel-distribution
> Upgrade bazel-distribution

- library/crates/BUILD.bazel
- library/crates/Cargo.toml
We pin the version of the regex crate and make it available through bazel.
> Add regex crate

- distribution/deps.bzl
Update bazel-distribution with rules that support for release candidate versioning.
- Update bazel-distribution
> Update bazel-distribution to support release candidates

- library/maven/artifacts.bzl
We add dependencies for performing JSON serialization during Ktor HTTP requests and contacting Stripe with Kotlin.
We add the required libraries: `stripe-java`, `ktor-client-content-negotiation-jvm`, and `ktor-serialization-gson-jvm`
> Stripe Java and Ktor JSON dependencies

- tool/release/deps/ValidateDeps.kt
- tool/release/deps/ValidateNodeJsDeps.kt
- tool/release/deps/ValidatePythonDeps.kt
- tool/release/deps/rules.bzl
We add a check to dependency validation before release to ensure releases don't depend on release candidates.
> Ensure releases don't depend on RC

- library/crates/Cargo.lock
- library/crates/Cargo.toml
We add dependency on the lz4 compression crate and regenerate the cargo lockfile.
> Add lz4 crate dependency

- library/crates/Cargo.lock
- library/crates/Cargo.toml
Introduce pprof required for criterion flame graphs.
Introduce pprof required for criterion flame graphs.
> Add pprof for rust benchmarking flame graphs

- library/maven/artifacts.bzl
> Newrelic dependencies

- library/maven/artifacts.bzl
> Newrelic telemetry libraries

- library/maven/artifacts.bzl
> Jackson date-time

- library/crates/Cargo.lock
- library/crates/Cargo.toml
Adds xoshiro as rust dev dependencies
* Adds xoshiro  as rust dev dependencies.
* Runs the update script.
> Add xoshiro as rust dev dependencies

- library/crates/Cargo.lock
- library/crates/Cargo.toml
Add rng_core required by xoshiro to rust dependencies
Add rng_core required by xoshiro to rust dependencies
> Add rng_core required by xoshiro to rust dependencies

- library/maven/artifacts.bzl
We add dependencies required to perform JWT auth through ktor
We add `io.ktor:ktor-server-auth-jvm`, `io.ktor:ktor-server-auth-jwt-jvm`, and `com.auth0:jwks-rsa` dependencies.
> Ktor server authentication dependencies

- library/maven/artifacts.bzl
We add the AWS SQS SDK for Kotlin
We add the `aws.sdk.kotlin:sqs-jvm` artifact
> AWS Kotlin SDK for SQS

- library/maven/artifacts.bzl
We add the AWS SDKs for Kotlin for interacting with the marketplace metering API 
We add the `aws.sdk.kotlin:marketplacemetering-jvm` artifact.
> Add AWS Marketplace SDKs for Kotlin

- library/maven/artifacts.bzl
Add Novu kotlin SDK
We want to use Novu to power notifications in TypeDB Cloud
Add required dependency
> Add Novu kotlin SDK
