typedb/typedb-dependencies

ci/sync_dependencies.py

1. make method name clearer that it contains credentials, for the eyes of developers
2. prevent grabl credential from being exposed in print statements

Prevent grabl credential from being exposed

---

distribution/dependencies.bzl

Bumps version of `@graknlabs_bazel_distribution` to include bugfixes:
graknlabs/bazel-distribution#47
graknlabs/bazel-distribution#67

Bump @graknlabs_bazel_distribution version

---

ci/sync_dependencies.py
distribution/dependencies.bzl

- All `DependencyReplacer::replace` implementations now replace a `list` of replaced files
- `PackageJsonDependencyReplacer` now scans for *all* `package.json` files to replace `client-nodejs` dependency in them

Improve PackageJsonDependencyReplacer to scan for all package.json-s

---

ci/sync_dependencies.py

Leftover code I forgot to remove was preventing new code from executing

Bugfix: PackageJsonDependencyReplacer should not check for old file location

---

ci/sync_dependencies.py

- uses $CREDENTIAL instead of passing a command-line argument
- commands have to be prefixed with `bash -c` so variable expansion happens

Read @grabl's credentials from environment instead of passing as cmdline

---

ci/release_approval.py

`release-approval.py` will fail because it is run from within the Bazel sandbox and won't have access to the workspace. This PR fixes the issue.
Here's an example of the error which was encountered when making a release draft for Workbase:
https://circleci.com/gh/graknlabs/workbase/678
```
Tests have been ran and everything is in a good, releasable state. It is possible to proceed with the release process. Waiting for approval.
..................................Release Approval received! Initiating release workflow ...
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
File "/home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/execroot/graknlabs_workbase/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci …
```

release-approval.py - fix working directory issue

---

ci/sync_dependencies.py

- `git_coordinates` is a string
- `coords` is a single-element string list

Bugfix sync_dependencies to properly unpack one-value list

---

deployment.properties

These keys are no longer relevant
`repo.github.*` — not common across multiple repos
`repo.pypi.tpypi` — we use our test repo instead of test PyPI

Remove obsolete property keys

---

deployment.properties

This switches `*.release` keys to have `*.test` values whereas preserving old values in comment

Test credentials in place of production URLs

---

.circleci/config.yml

Auto-update benchmark dependencies to reflect updates to build-tools. This should lead to notifications when benchmark fails because of a breaking change rather than having to notice that the dashboard is not updating anymore.
* Add benchmark:master to sync dependencies

Add benchmark:master to sync dependencies

---

checkstyle/test-coverage.py
ci/release-approval.py
ci/sync-dependencies.py

Improve error reporting in `test-coverage.py`, `release-approval.py`, and `sync-dependencies.py` in the following ways:
- Ensure `stderr` is captured and not discarded which will make debugging much easier.
- Eliminate various scenarios where the script can fail silently when making a failed HTTP request due to incorrect credentials.
`release-approval.py` has been updated to accept Github username and token which can be supplied via the `$RELEASE_APPROVAL_USERNAME` and `$RELEASE_APPROVAL_TOKEN` environment variables. This is an improvement to the old approach of needing SSH keys which is more cumbersome to generate and supply.
Closes https://github.com/graknlabs/build-tools/issues/34 and https://github.com/graknlabs/build-tools/issues/35

Improve error reporting and remove the need to supply SSH keys

---

ci/BUILD
ci/test-cache.py

Helps fixing graknlabs/grakn#5079
Results of testing assembled distribution are now cached. Therefore, tests for same distribution archive are not triggered more than once if has a successful run, which speeds up overall CI execution for `master` branch.
Added `//ci:test-cache` binary target. Example invocations:
`bazel run @graknlabs_build_tools//ci:test-cache -- --file $(pwd)/bazel-bin/grakn-core-all-mac.zip --get`
`bazel run @graknlabs_build_tools//ci:test-cache -- --file $(pwd)/bazel-bin/grakn-core-all-mac.zip --save-success`
Note the importance of `$(pwd)` since running is done inside the sandbox.

Script for caching distribution test results

---

BUILD
checkstyle/BUILD
checkstyle/test-coverage.py
ci/BUILD
ci/release-approval.py
ci/sync-dependencies.py
common.py

Introduces `common.py` to hold functions used across the codebase. This should reduce code duplication and make the codebase more maintainable
`shell_execute` no longer merges stderr into stdout. Instead it returns `stdout` and `stderr` in a separate variables. If exit code is non-zero, it will throw / raise a `RuntimeError`:
```
try:
stdout, stderr = common.shell_execute(['bazel', 'test', '//...'])
except RuntimeError:
...
```

Introduces `common.py` to hold functions used across the codebase. `shell_execute` no longer merges stderr into stdout

---

ci/BUILD
ci/sync-version.py

Fix #47 
This is a tool that helps incrementing version in version file across @graknlabs repos. Currently, only incrementing **patch** (following [semantic versioning](https://semver.org) terminology) version is supported.
Sample usage:
```
py_binary(
name= "sync_version",
srcs = ["@graknlabs_build_tools//ci:sync-version.py"],
data= ["//:VERSION"],
main = "ci/sync-version.py",
args = ["$(location //:VERSION)"]
)
```
```
ghost:grakn vmax$ bazel run //:sync_version
INFO: Analyzed target //:sync_version (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:sync_version up-to-date:
bazel-bin/sync_version
INFO: Elapsed time: 0.200s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total …
```

Implement sync-version tools

---

BUILD
ci/rbe-image/Dockerfile
ci/rbe-image/README.md

* Improves maintainability by having consistency across all targets: no targets are built locally on CI, RPM of Grakn Core will be built remotely as well
* Improve performance by caching the RPM target of Grakn Core

Custom Docker image for RBE

---

bazel/BUILD
bazel/SingleJar.java

This is the first step to fixing graknlabs/grakn#4851
`singlejar` wrapper (`@graknlabs_build_tools//bazel:singlejar`) detects when `singlejar` is called to build a source JAR and modifies command-line arguments so that source file is placed with respect to `package` statement in it.
For class `com.smth.Main` *incorrect* (from IntellIJ”s standpoint) structure (and this is something that is currently produced) would be:
```
ghost:b vmax$ jar tf bazel-bin/main-src.jar
META-INF/
META-INF/MANIFEST.MF
Main.java
```
Correct source JAR (that would actually be picked up) would look like this:
```
ghost:b vmax$ jar tf bazel-bin/main-src.jar
META-INF/
META-INF/MANIFEST.MF
com/
com/lib/
com/lib/Main.java
```

Implement SingleJar wrapper and include it in custom Java toolchain

---

bazel/BUILD

Building Grakn Core on Windows was broken by a recent introduction of custom java toolchain in #51. This means that you weren't able to run `bazel build ...` on a Windows machine. As a consequence `test-assembly-windows-zip` is also broken. This pull request specifies correct version of `singlejar` to un-break the build.
Relevant error message:
```
ERROR: C:/users/circleci/_bazel_circleci/xuhrud3v/external/graknlabs_build_tools/bazel/BUILD:53:1: no such target '@bazel_tools//tools/jdk:singlejar/singlejar': target 'singlejar/singlejar' not declared in package 'tools/jdk' (did you mean 'singlejar/singlejar.exe'?) defined by C:/users/circleci/_bazel_circleci/xuhrud3v/external/bazel_tools/tools/jdk/BUILD and referenced by '@graknlabs_build_tools//bazel:singlejar'
```
Specify the same version …

Specify original version of singlejar for Windows builds

---

ci/install-bazel-mac.sh

Latest XCode image for CircleCI (`10.1`) does not have installed JDK, which prevents `bazel` to build code (relevant issue: https://github.com/bazelbuild/bazel/issues/7304). This PR adds installing `AdoptOpenJDK8` via Homebrew, un-breaking the build.

Install JDK for Mac CI builds

---

bazel/BUILD
bazel/SingleJar.java

Build failed on `bazel` `v0.26.0` with the following error:
```
ERROR: /private/var/tmp/_bazel_enricoboccadifuoco/3aac2f4ba9b1e5eaf21b07e0e0d63f02/external/graknlabs_build_tools/bazel/BUILD:54:1: no such target '@bazel_tools//tools/jdk:singlejar/singlejar': target 'singlejar/singlejar' not declared in package 'tools/jdk' defined by /private/var/tmp/_bazel_enricoboccadifuoco/3aac2f4ba9b1e5eaf21b07e0e0d63f02/external/bazel_tools/tools/jdk/BUILD and referenced by '@graknlabs_build_tools//bazel:singlejar'
```
This pull request introduces `singlejar` definition compatible with both `v0.25.2` which is currently used by us and `v0.26.0` which is the next version.

Adapt to newest singlejar placement in bazel v0.26.0

---

bazel/BUILD
bazel/SingleJar.java

In order to support building Grakn on all platforms on both `v0.25.2` and `v0.26.0` of `bazel`, same `singlejar` should be used. This PR brings support for `.exe` versions of `singlejar` for Windows into our custom `singlejar` and unifies the source jar building process on all platforms.

Use same singlejar binary on all platforms

---

ci/run-bazel-rbe.py

To fix #326, `//ci:run-bazel-rbe` will be utilized. However, RBE does not support building for Mac, failing with the following error:
```
ERROR: /private/var/tmp/_bazel_vmax/d2feb27241ea51489aa2f0591c0e06e6/external/bazel_toolchains/configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc/BUILD:45:1: in cc_toolchain_suite rule @bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc:toolchain: cc_toolchain_suite '@bazel_toolchains//configs/ubuntu16_04_clang/9.0.0/bazel_0.25.2/cc:toolchain' does not contain a toolchain for cpu 'darwin'
```
Therefore, RBE builds on non-Linux systems will be ignored even if gcloud config file is present.

run-bazel-rbe should account for platform it is running on

---

WORKSPACE

graknlabs/bazel-distribution#132 introduced a dependency on `@io_bazel_skydoc` which broke the CI of `build-tools` (resulting in not being able to resolve `@bazel_skylib`). This pull requests pulls in same dependencies so CI does not fail.

Add missing transitive dependency to io_bazel_skydoc

---

checkstyle/config/BUILD
checkstyle/config/checkstyle-file-header-grakn-kgms.txt
checkstyle/rules.bzl

In order to use `checkstyle_test` with Grakn KGMS codebase, it should support KGMS's license header:
```
/*
* Copyright (c) Grakn Labs, 2019
*
* This unpublished material is proprietary to Grakn Labs.
* All rights reserved. The methods and
* techniques described herein are considered trade secrets
* and/or confidential. Reproduction or distribution, in whole
* or in part, is forbidden except by express written permission
* of Grakn Labs.
*/
```

checkstyle_test: support Grakn KGMS proprietary license header

---

bazel/SingleJar.java

Fixing some unknown changes in `bazel` which prevented us from deploying Maven artifacts due to file permission issue (`java.nio.file.FileSystemException: bazel-out/k8-fastbuild/bin/api/libapi-src.jar-0.params: Read-only file system`).
Previously, `.params` file [produced by `bazel`] was rewritten in-place. This PR writes contents of it to a separate temporary file and modifies argument to reference it instead.

Fixing some unknown changes in `bazel` which prevented us from deploying Maven artifacts

---

distribution/maven/BUILD
distribution/maven/rules.bzl

- Use `@graknlabs_bazel_distribution//maven:deployment_rules_builder` (proper `py_binary` target) instead of `@graknlabs_bazel_distribution//maven:deployment_rules_builder.py` (exported Python script): introduced in graknlabs/bazel-distribution#143
- Run `distribution/maven/update.sh` to sync `rules.bzl`

Sync rules with latest @graknlabs_bazel_distribution

---

distribution/maven/rules.bzl

- Run `distribution/maven/update.sh` to sync `rules.bzl` so that graknlabs/bazel-distribution#145 is included

Sync Maven rules with latest @graknlabs_bazel_distribution

---

grpc/dependencies.bzl

In order to use `python_grpc_library`, we need to bump version of `@stackb_rules_proto` to include https://github.com/stackb/rules_proto/commit/e783457abea020e7df6b94acb54f668c0473ae31. Otherwise, supplying `--incompatible_disallow_dict_plus` to every `bazel` invocation would be required.

Upgrade @stackb_rules_proto to fix bazel incompatibility

---

bazel/dependencies.bzl

This is needed to have support for `vendor_external` argument in `npm_package` introduced in https://github.com/graknlabs/rules_nodejs/commit/ae55e5b839aad78dd12a11ea4fe9601664c40a9 (backported from upstream)

Upgrade @bazel_build_rules_nodejs to latest graknlabs/rules_nodejs#experimental

---

bazel/dependencies.bzl

Since `graknlabs/rules_nodejs` is going to be deprecated, we're reverting to most-recent version of `@build_bazel_rules_nodejs`

Revert to upstream rules_nodejs

---

ci/install-bazel-linux.sh
ci/install-bazel-mac.sh

Upgraded `rules-nodejs` require `bazel 0.26.0` as minimal supported version. Due to us not being able to use `0.27.0` and further versions (rel issue: bazelbuild/bazel#8659), we're using `0.26.1`

Upgrade bazel to 0.26.1

---

ci/install-bazel-rbe.sh

Fixes #77 
The logic is as follows:
- if build is *not* an RBE build:
- if platform is Linux:
- `apt-get install rpm`
- if platform is Darwin:
- `brew install rpm`
- else
- fail

Make sure builds executed locally don't fail

---

ci/BUILD
ci/apt-wait.sh

Sometimes, our CI job which installs dependencies using `apt` would fail because the machine may perform an initial `apt` update in the background. This PR adds `apt-wait.sh` for waiting for an existing `apt` to finish.

Add apt-wait.sh, which waits for an existing apt process to finish

---

ci/release-approval.py

Fixes #85 
Apparently, `hmac.new` now only accepts encoded `bytes` (as opposed to `str` in Python 2). Calling `.encode()` on first two arguments is supported in both Python versions.

Make release-approval script Python 2/3 compatible

---

ci/release-notes.py

[This run of CI](https://circleci.com/gh/graknlabs/protocol/238) failed since some PRs contained non-ASCII chars and therefore failed with the following stacktrace:
```
Traceback (most recent call last):
File "/home/circleci/.cache/bazel/_bazel_circleci/9f69b2e90a3e4f79cd001380bef9d42c/execroot/graknlabs_protocol/bazel-out/k8-fastbuild/bin/external/graknlabs_build_tools/ci/release-notes.runfiles/graknlabs_build_tools/ci/release-notes.py", line 110, in <module>
filepath.write(release_notes_content)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1267-1268: ordinal not in range(128)
```
This PR opens the output file with correct encoding so this error can be avoided.

Allow release notes to contain UTF8 chars

---

ci/BUILD

Fix #74 
`certifi` is now included to `deps` of `release-notes`

Add certifi as a dependency of //ci:release-notes

---

ci/install-bazel-rbe.sh

To increase build time and not install `rpmbuild` which is not needed is build is executed remotely

Install rpmbuild conditionally

---

ci/release-approval.py

For proper output on CircleCI, we now print `...` and a newline every minute rather than `.` every second

Modify how we visually indicate for input

---

ci/BUILD
ci/release-validate-deps.py

The `//ci:release-validate-deps` can be used from the CI job to ensure that we're depending on a release instead of a snapshot dependency.
For example, if we are to release `graknlabs_grakn_core` which depends on a snapshot version of `graknlabs_common` will fail with the following error message:
```
bazel run @graknlabs_build_tools//ci:release-validate-deps graknlabs_graql graknlabs_common
RuntimeError: This commit is not releasable because there are one or more snapshot 
dependencies: ['graknlabs_common']. Check that every dependencies listed in 
dependencies/graknlabs/dependencies.bzl are all release dependencies 
(ie., depends on a tag instead of a commit).
```
If every dependency is a release dependency, it will succeed:
```
bazel run @graknlabs_build_tools//ci:release-validate-deps …
```

Implement //ci:release-validate-deps

---

ci/sync-dependencies.py

As we now run all Bazel target with Python 3, fixing of `sync-dependencies` is required. Similarly to how it was done in #86, we now pass `bytes` to `hmac.new`

Adapt sync-dependencies to run with Python 3

---

sonarcloud/code-analysis.py

Python 3's version of `subprocess.check_call` returns `bytes` which need to be decoded before using as path component. To fix it, we use native method to create a temporary directory: `tempfile.mkdtemp()`

Fix code-analysis script to work with Python 3

---

ci/test-cache.py

`//ci:test-cache` was non-operational due to incorrect usage of `hashlib`
`hashlib.<algo>` expects `bytes` to calculate checksum of, so we open files in "read binary" (`rb`) mode

Fix //ci:test-cache to work with Python 3

---

WORKSPACE

Recent `sync-dependencies` from `bazel-distribution` broke CI. This PR fixes it by loading `@rules_pkg`

Fix CI by loading rules_pkg repo

---

ci/test-cache.py

`RELEASE_APPROVAL_TOKEN` was not a proper name for a varialbe to be used in `//ci:test-cache` mainly because its purpose is not clear from its name. This PR names the variable properly.

Rename variable used to sign message in //ci:test-cache

---

WORKSPACE
unused_deps/BUILD
unused_deps/dependencies.bzl
unused_deps/unused_deps.py

Fix #103
Sample usage:
```
bazel run @graknlabs_build_tools//unused_deps -- list
```
```
bazel run @graknlabs_build_tools//unused_deps -- remove
```

Detect unused Java dependencies

---

bazel/dependencies.bzl

Previously, we could not release `1.6.0` due to old `rules_docker` depending on Python 2. In the newest release, `pusher` binary was replaced with Go binary, so we upgrade.

Upgrade @io_bazel_rules_docker to latest release

---

grpc/dependencies.bzl

In order to use upgraded `grpc`, we need to add a link to `io_grpc_grpc_java` such that `1.24.1` is used instead of `v1.19.0` pulled in by `rules_proto`. This allows us to not have to fork and maintain `rules_proto`

Link 1.24.1 of @io_grpc_grpc_java

---

distribution/maven/rules.bzl

`build-tools` need to include fixes from graknlabs/bazel-distribution#209

Sync Maven distribution rules to latest bazel-distribution

---

grpc/dependencies.bzl

Linked commit already contains fix for Maven HTTPS issue: https://github.com/graknlabs/grpc-java/commit/62e8655f1bc4dfb474afbf332ca7571c1454e6ef
This commit is chosen as the commit closest to 1.24.1, which is the gRPC version that we use.

Bump @io_grpc_grpc_java to a version with maven-https fix

---

checkstyle/dependencies.bzl

Bazel 2.0 removes `maven_jar` from native rules. In order for us to migrate to newer Bazel, `checkstyle_dependencies` need to be adapted according to guide in bazelbuild/bazel#6799

Remove incompatible native.maven_jar usage

---

library/maven/artifacts.bzl
library/maven/rules.bzl

We have supported excluding artifacts in `library/maven/artifacts.bzl`:
```
artifacts = {
"ch.qos.logback:logback-classic": "1.2.3",
"org.zeroturnaround:zt-exec": { # 
"version": "1.10",
"exclude": [
"commons-io:commons-io",
],
}
}
```
Additionally, we've added more Maven dependencies used by various repositories across Grakn Labs

Support excluding artifacts. Add a large amount of Maven dependencies required by most Grakn Labs repositories

---

library/maven/artifacts.bzl

We would like to use Picocli in our projects to do command line interfaces in a consistent way that supports subcommand hierarchies.
- Add Picocli maven dependency

Add Picocli maven dependency

---

WORKSPACE
builder/kotlin/deps.bzl
library/maven/BUILD
library/maven/update.kt

We have implemented a script to update Maven's `artifacts.snapshot` file.
Usage example:
```
$ bazel run @graknlabs_dependencies//library/maven:update
-------------------------
Regenerating a new '/Users/lolski/grakn.ai/graknlabs/grakn/dependencies/maven/snapshot' from WORKSPACE...
DONE! '/Users/lolski/grakn.ai/graknlabs/grakn/dependencies/maven/snapshot' updated: 4 dependencies added, 1 dependencies removed.
Added dependencies:
- @maven//:com_boundary_high_scale_lib
- @maven//:com_boundary_high_scale_lib_1_0_6
- @maven//:com_github_jbellis_jamm
- @maven//:org_ow2_asm_asm_5_0_4
Removed dependencies:
- @maven//:io_dropwizard_metrics_metrics_jvm_3_1_2
-------------------------
```

Implement Maven's artifacts.snapshot update script

---

WORKSPACE

We have refactored the WORKSPACE file such that the code that imports `@bazel_distribution` follows a more uniform structure.
It now follows [this structure](https://github.com/graknlabs/bazel-distribution/blob/a87ddc364ad35fd913714f001ac4eb2694a215c8/WORKSPACE) more closely.

Refactor WORKSPACE

---

distribution/artifact/rules.bzl
distribution/artifact/templates/BUILD
distribution/artifact/templates/deploy.py
distribution/deployment.properties

We want to move the artifact distribution rules from bazel-distribution to here because they need to be very graknlabs specific.

Add artifact rules (moved from bazel-distribution)

---

distribution/artifact/rules.bzl
distribution/artifact/templates/deploy.py

We need to be able to publish artifacts with versioned filenames and including help for this logic in the `artifact` rules will significantly improve development experience. The solution we've gone for is to allow the version to be interpolated into the artifact filename, since this can be the same on both sides of the rule (deploy/depend), works in static rules (no file dependencies), is very flexible on filename format and has very clear visibility on what the resulting filename will look like.

Add version interpolation to artifact rules

---

distribution/artifact/rules.bzl
distribution/artifact/templates/deploy.py

We need to be able to extract an artifact depended on via artifact rules on the command line in CI. This is tricky without some bazel magic, so we've created a macro that can use bazel specific logic to generate an executable script that performs this logic for us. This plays by all of bazel's rules to avoid non-hermetic builds.

Add extract script generation macro

---

library/jmh/BUILD
library/jmh/artifacts.bzl
library/jmh/rules.bzl
library/maven/artifacts.bzl

JMH is a common tool for benchmarking Java applications, so we are adding it to this repo to make it available to our other repos.

Add JMH benchmarking library and rules

---

library/maven/artifacts.bzl

We are planning to use ZeroMQ (implemented with the JeroMQ library for Java) as our cluster fabric (node to node networking). This PR adds the dependency to make it available to downstream repositories.

Add jeromq maven dependency.

---

tool/bazelinstall/rbe.sh

* `-s` option ignores potentially-installed version whch helps with reruns
* setting Python2's version as one that's installed in system helps us be cross-compatible with both CircleCI and Grabl

Fix pyenv to be cross-compatible between CircleCI and Grabl

---

library/maven/rules.bzl

We still have old maven repository URLs in our maven rules. This will always fail if we try to fall back to it.

Update our maven repository URLs

---

WORKSPACE
builder/bazel/BUILD
builder/bazel/deps.bzl

`@com_github_google_bazel_common` and `bazel-deps` are now universally not used, so they need to be removed

Remove bazel-deps and bazel-common

---

tool/release/validate-deps.py

We've in process of moving `dependencies/graknlabs/dependencies.bzl` to `dependencies/graknlabs/repositories.bzl` so `@graknlabs_dependencies//tool/release:validate-deps` need to be tweaked accordingly

Use new name for file with Bazel workspace dependencies

---

tool/bazelinstall/rbe.sh

* BuildBuddy credential path is adjusted to be `/opt/.credentials`
* `pyenv` (on Grabl) no longer needs an additional `git pull` command

Tweak tool/bazelinstall/rbe.sh

---

tool/bazelinstall/rbe.sh

Fixes this CircleCI error:
>python-build: definition not found: 3.6.10
>See all available versions with `pyenv install --list'.
>If the version you need is missing, try upgrading pyenv:
>    cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd -

Restore pyenv cloning in tools/bazelinstall/rbe.sh

---

tool/bazelinstall/rbe.sh

Makes rbe.sh compatible with both CircleCI and Grabl

Make pyenv-related command cross-compatible

---

tool/release/BUILD
tool/release/ValidateDeps.kt

The tagged_deps field has been made to strictly accept input in the following format: `@graknlabs_common`, and not `graknlabs_common`

Restrict the input for the tagged_deps field of release_validate_deps

---

dependencies/graknlabs/repositories.bzl

Bump deps of bazel-distribution including bug fix for assemble-npm, following on from https://github.com/graknlabs/bazel-distribution/pull/254

bump deps of bazel-distribution including bug fix for assemble-npm

---

distribution/artifact/rules.bzl

As we may need to extract `.zip` artifacts (for Windows), the `artifact_extractor` has been extended to choose a decompression tool according to the file's extension.
- added unzip script
- the extract file extension and use  the right script to decompress it

Extends artifact_extractor to support zip decompression

---

tool/checkstyle/config/checkstyle-file-header-agpl.txt
tool/checkstyle/config/checkstyle-file-header-apache.txt
tool/checkstyle/config/checkstyle-file-header-grakn-kgms.txt
tool/checkstyle/rules.bzl
tool/checkstyle/test-coverage.py

To make checkstyle_test work with any file type
Deleted `targets` and `files`. Added `include` and `exclude`. They both take in a list of files (e.g. via a `glob`).
If a file is present in `include` it will be checked by checkstyle, unless it is also present in `exclude`. If a file is present in `exclude`, it will not be checked by checkstyle. If a file is present in neither `include` nor `exclude`, an error will be thrown by `checkstyle:test-coverage`.

Make checkstyle_test work with any file type

---

tool/checkstyle/rules.bzl
tool/checkstyle/test-coverage.py

To not require license headers in MD files
Exclude all MD files from checkstyle and test-coverage

Exclude all MD files from checkstyle

---

library/maven/rules.bzl

Previously, source JARs won't be fetched by `rules_jvm_internal` which made it impossible to _Go to source_ in IntelliJ.
Configure `rules_jvm_internal` to fetch source JARs as well

Make maven_install fetch source JARs as well

---

tool/checkstyle/config/checkstyle-file-header-agpl.txt
tool/checkstyle/config/checkstyle-file-header-apache.txt
tool/checkstyle/config/checkstyle-file-header-grakn-kgms.txt
tool/checkstyle/templates/checkstyle.xml

To allow Bash scripts to pass checkstyle tests (i.e. shell scripts that are instructed to execute in Bash)
Each of our license templates now has `^#!.*` as line 1, while `checkstyle.xml` defines line 1 as a `multiLine`, meaning it is allowed to match zero or more times.
As a result, hashbangs are now allowed at the start of Checkstyle targets.
Example shell script (passing the new checkstyle test):
```
#!/usr/bin/env bash
#
#
```

Allow hashbangs at the start of Checkstyle targets

---

library/rocksdbjni/BUILD
library/rocksdbjni/RocksDbBuilder.kt

We have removed the hard-coded `JAVA_HOME` in `RocksDbBuilder.kt`. It is now retrieved dynamically with `/usr/libexec/java_home`.
This is something that wasn't possible before and is only made possible by making Java available within the sandbox. Specifically, we're talking about adding Java toolchain in the `tools` attribute (which apparently was already added in the [original PR](https://github.com/graknlabs/dependencies/pull/203) for a seemingly different reason):
```
genrule(
name = "builder",
...
tools = ["@bazel_tools//tools/jdk:current_host_java_runtime", ":build-script"],
)
```

Remove hard-coded Java path

---

builder/java/rules.bzl

To allow all five of the following operations to succeed in Grakn Core 2.0 since bringing in Google ORTools, which provides only native (platform-specific) JARs:
1. Building a Windows, Mac or Linux distribution on any machine, even if the target platform is different to the host platform
2. Compiling the project locally in IntelliJ using, say, `bazel build //...`
3. Running the tests locally
4. Compiling the project in Grabl
5. Running the tests in Grabl
We add three new Bazel macros:
Replaces `java_library`. This macro expands to 3 platform-native `java_library` targets. For example:
```
native_java_libraries(
name = "pattern",
srcs = glob(["*.java"]),
deps = ["//common:common"],
native_libraries_deps = ["//traversal:traversal"]
)
```
expands to:
```
java_library(
name = "pattern-mac", …
```

Add native_java_libraries and host_compatible_java_library

---

tool/bazelinstall/rbe.sh

Currently, there is an assumption embedded into `tool/bazelinstall/rbe.sh`: if we're running on Linux, it must be Ubuntu. However, as we're integrating CentOS into our workflow, this assumption no longer holds true - it doesn't have `apt-get` and it already has `rpmbuild` (which, consequently, doesn't need to be installed there as it's already present)
Only install `rpmbuild` if it's not present yet.

Make RBE script portable (to support CentOS)

---

builder/nodejs/deps.bzl

Update bazel build rules nodejs for benefit of protocol compilation
Upgrade to rules_nodejs 2.2.2 in builder/nodejs

Upgrade nodejs build rules

---

tool/checkstyle/test-coverage.py

To fix checkstyle:test-coverage failing in projects that use `npm`
Exclude node_modules and .idea from checkstyle:test-coverage

Don't subject node_modules to checkstyle:test-coverage

---

grabl/analysis/DependencyAnalysis.kt

Currently file where external repo dependencies are declared is named `repositories.bzl`; dependency analysis script still uses the old name to read them.
Rename `dependencies.bzl` to `repositories.bzl`

DependencyAnalysis: update dependency filename

---

grabl/analysis/DependencyAnalysis.kt

Currently, even successful executions of `dependency-analysis` fail the job. It happens because we tell `curl` to redirect output to the wrong stream (stderr instead of stdout).
Make `curl` output exit code to `stdout` (which is later matched with "202")

Fix dependency-analyis false-negative results

---

grabl/analysis/DependencyAnalysis.kt

Currently, even successful executions of `dependency-analysis` fail the job. It happens because we expect the code to be 
`202` rather than `201`.
* Accept `201` as successful code
* Ease debugging by printing the output we get from `curl`

Fix dependency-analysis for good

---

WORKSPACE
tool/common/deps.bzl

Ensure Maven artifacts are loaded from the same place where other repos could find them too: `//tool/common:deps.bzl`.
* Update `maven_artifacts` in `tool/common/deps.bzl` to reflect actual Maven dependencies of `graknlabs_dependencies`
* Load Maven artifacts from `tool/common/deps.bzl` instead of specifying directly in `WORKSPACE`

Update how Maven dependencies are loaded

---

distribution/artifact/rules.bzl

Currently, it's impossible to fetch Windows artifact with `native_artifact_files` macro
Include `windows` as platform to pull artifacts for

Pull in graknlabs_grakn_core artifact for Windows

---

image/buildbuddy/BUILD
image/buildbuddy/Dockerfile

Currently, there is a need to upgrade our builds to be done on recent Ubuntu (20.04) and Java 11. This requires a custom Java image.
* Add `//image/buildbuddy` package to store `platform` in
* `Dockerfile` to build an image with all our build dependencies

BuildBuddy Ubuntu 20.04 image to do builds on

---

.bazelrc
.grabl/automation.yml

In order to speed up our builds, we should do them remotely on BuildBuddy
Tweak `.bazelrc` settings to build on BuildBuddy with our own Ubuntu 20.04 image

Build remotely on Ubuntu 20.04

---

tool/bazelinstall/mac.sh

Currently, installing Bazel under Mac in CI (for example, in Core) fails with `Error: Calling brew cask install is disabled! Use brew install [--cask] instead.` message.
Apply the suggestion and install cask correctly

Fix tool/bazelinstall/mac.sh

---

tool/release/BUILD
tool/release/ValidatePythonDeps.kt
tool/release/rules.bzl

Currently, it's possible to release a Python package which still depends on a snapshot version (say, from `repo.grakn.ai`). In order to prevent it, we need to run a test which goes over `requirements.txt` and verifies that dependencies are properly versioned.
Implement `release_validate_python_deps`; sample usage:
```
release_validate_python_deps(
name = "release-validate-python-deps",
requirements = "//:requirements.txt",
tagged_deps = ["graknprotocol"]
)
```

Implement validation of Python dependencies

---

tool/release/docs.py

As we've renamed `web-dev` to `web-docs`, a release tool we use also needs to be updated.
Update `web-dev` references to `web-docs`

Change web-dev to web-docs

---

library/maven/artifacts.bzl

Fix `WARNING: An illegal reflective access operation has occurred` warning caused by an out of date version of protobuf.
- Update protobuf to latest.

Fix console warnings caused by out of date dependency

---

distribution/deps.bzl
tool/release/ValidatePythonDeps.kt

Similarly to graknlabs/bazel-distribution#281, we want to ignore `--extra-index-url` line in `requirements` file that we pass to `release_validate_python_deps`.
Ignore lines beginning with `--` and bump `@graknlabs_bazel_distribution` to latest `master`

Fix release_validate_python_deps

---

tool/bazelinstall/rbe.sh

We no longer build RPMs which means installing `rpm` is only going to slow the build down without providing any significant value. Additionally, as we no longer build on Circle and similar issue has been addressed in graknlabs/grabl#1993, we no longer need a function that waits for APT to finish.
Remove `apt_wait`, `install_dependencies` and CircleCI-specific setup from `rbe.sh`

Cleanup rbe.sh script

---

distribution/docker/BUILD
distribution/docker/bazelbuild-rules-docker-fix-tarfile-format.patch
distribution/docker/deps.bzl

Patch `rules_docker` in order for us to be able to build Docker image for Grakn Cluster.
Patch `rules_docker` such that an image can be built

Fix Docker rules for Grakn Cluster

---

tool/bazelinstall/rbe.sh

Allow our repositories to use Bazel cache we host ourselves at https://bazel.grakn.ai
Configure the Bazel cache for the build if `$BAZEL_CACHE_URL` environment variable is found

Support self-hosted Bazel remote cache

---

tool/util/wait-for-host.sh

For Grakn Cluster, we would need to wait for host becoming available.
Implement `wait-for-host.sh` which repeatedly `ping`s the specified host

Add script for waiting for host availability

---

distribution/docker/deps.bzl

Upgrade rules for building Docker images to help upgrade whole build infrastructure (Bazel 4.0.0, Java 11)
Bump `rules_docker` version to `0.16.0` (latest release)

Upgrade @rules_docker to latest release

---

tool/bazelinstall/linux.sh
tool/bazelinstall/mac.sh

Upgrade Bazel versions in `tool/bazelinstall` to latest release of Bazel.
Bump the Bazel version to 4.0.0
Remove unneeded installation of Java 8 in macOS-specific script

Upgrade Bazel to 4.0.0

---

distribution/helm/deps.bzl

Use upstream repo for Helm rules
As our changes are accepted into https://github.com/masmovil/bazel-rules we can now proceed with using upstream rules.

Revert Helm repo to upstream

---

distribution/docker/deps.bzl

Propogate the bugfix in `rules_pkg` via `rules_docker`
Upgrade `rules_docker` to our forked version with all the needed changes (`vaticle` branch)

Bump version of @io_bazel_rules_docker

---

tool/requirements.txt

To fix deployment issues, we have to bump PyGithub to 1.55
Use lates pygithub relesae

Bump pygithub to 1.55

---

library/maven/artifacts.bzl
library/maven/update.kt
tool/checkstyle/deps.bzl
tool/checkstyle/rules.bzl

Previously in #295 we used the wrong way to import Guava 30.1, we correctly use 30.1-jre insted of guava-jre with version 30.1
* Update to version 30.1 correctly
* regenerate the sha256 for the checkstyle dependency, which also uses version 30-jre instead of the old version 23

Guava 30.1 needs to use 30.1-jre version

---

library/maven/artifacts.bzl

Unblock Grabl builds by using a version of Maven libraries can be downloaded.
For the unknown reason, Grabl builds now fail with this error:
```
ERROR: Error fetching repository: Traceback (most recent call last):
File "/home/circleci/.cache/bazel/_bazel_circleci/a22eaad070d73c89945f8e63b8f1272e/external/rules_jvm_external/coursier.bzl", line 544, column 13, in _coursier_fetch_impl
fail("Error while fetching artifact with coursier: " + exec_result.stderr)
Error in fail: Error while fetching artifact with coursier: Resolution error: Error downloading com.azure:azure-storage-blob:12.6.0
```
After some investigation, it looks like there's an open issue for fixing it upstream: Azure/azure-sdk-for-java#23616
In order to unblock our builds, we upgrade by one minor version which **is** available …

Bump versions of Azure Storage Maven libraries

---

library/maven/artifacts.bzl

Add Maven libraries needed to allow TypeDB Cluster to output logs into Logstash.
- Add `net.logstash.logback:logstash-logback-encoder` for adding Logstash support
- Add `org.codehaus.janino:janino` for adding if conditionals support in `logback.xml`

Integrate libraries to support logging to Logstash

---

tool/release/createnotes/CreateNotes.kt
tool/release/createnotes/Note.kt

We fix release-note creation by escaping the notes inserted into the release template. The create-notes process used a regex to perform string replacement, which was not treating the replacement value as a literal string, but a regex as well, leading to errors. We also reverse the commits before generating the notes, so we get most-recent-first in the generated github release.
* escape the regex replacement string (ie. the notes markdown)
* reverse the order of commits before generating the release notes, so we get most recent commits first rather than last

Update create-notes to escape notes and use time-ordering

---

tool/release/deps/rules.bzl

We fixed the `release_validate_deps` rule which was broken due to a recent refactor.
Updated the package and Bazel targets that we forgot to update in the refactor.

Fix incorrect packages and Bazel targets

---

library/maven/artifacts.bzl

We upgraded `skiko-jvm-runtime-*` (now named `skiko-awt-runtime-*`)
Upgrade Skiko JVM Runtime (now named AWT Runtime)

Upgrade Skiko JVM Runtime (now named AWT Runtime)

---

.bazelrc

We disabled importing RBE credentials due to an expired cert, but should reintroduce them in the future.
Don't import RBE credentials

Fix expired cert error, temporarily

---

tool/release/version/BUILD
tool/release/version/Bump.kt

`//release/version:bump` no longer creates a GitHub milestone, and now pushes to the remote Git repo.
Previously, `//release/version:bump` behaved oddly, modifying the `VERSION` file but not committing the result to any repo. So we rebuilt it. The behaviour of the rule is:
1. Increment the number in the `VERSION` file
2. `git commit`
3. `git push`

Make 'release version bump' tool push to the remote Git repo

---

distribution/deps.bzl
library/maven/artifacts.bzl

We added the Maven artifact `org.jetbrains.skiko:skiko-awt`, which Studio uses. We also updated `bazel-distribution`, which means that duplicate Maven coordinates are now detected in `java_deps` and will fail the build.
- Add Maven artifact: org.jetbrains.skiko:skiko-awt
- Update bazel-distribution

Add Maven artifact: org.jetbrains.skiko:skiko-awt

---

builder/rust/deps.bzl

We update the `rules_rust` dependency to the most recent version. This has an effect of updating the default Rust version from 1.58.1 to 1.62.1.
The dependency fetch step is updated as per [the release page.](https://github.com/bazelbuild/rules_rust/releases/tag/0.9.0)

Update rules_rust to version 0.9.0

---

distribution/docker/deps.bzl

Bump the version of rules_docker and stop depending on Vaticle's fork. The issue that forced Vaticle to create the fork is already resolved in rules_docker. 
* Bump the version of rules_docker

Bump rules_docker and stop depending on Vaticle's fork

---

.factory/automation.yml
distribution/deps.bzl

We've updated bazel-distribution to propagate changes that update our use of Python. See the changes: 
- https://github.com/vaticle/bazel-distribution/pull/358
We've updated bazel-distribution and changed the Ubuntu 21.04 image to 22.04.
We don't intend to commit the given change - this will pass as a CI run and once the PR for dependencies is merged, we will change our destination repository and hash.

Bump bazel-distribution

---

ide/rust/BUILD
ide/rust/RepoCargoManifestGenerator.kt

We fixed the IDE sync tool generating binary names that are illegal in `Cargo.toml`, and made the sync tool have `public` visibility so that other repos can verify it.
Generated binary names are based on their project-relative path, ensuring uniqueness. But, they contained slashes, which are illegal in a `Cargo.toml` `[bin.name]`. So we now replace them with underscores.
Also, we've made the sync tool `public` so that other repos can declare it in their `:ci` `BUILD` targets.

Fix IDE sync tool generating binary names that are illegal in Cargo.toml

---

library/rocksdbjni/BUILD

We added the `manual` tag to `//library/rocksdbjni:assemble-maven-mac`. Previously, it didn't have this tag, so even though every other `rocksdbjni` target did, it was still getting compiled by `bazel build //...`. We also added "no-ide" to all rocksdbjni targets so that IDE tooling will ignore them.
Because the "manual" tag wasn't set on `//library/rocksdbjni:assemble-maven-mac`, it was getting compiled by `bazel build //...` which dramatically increases the build time (it takes roughly 6 minutes to build this target alone). Now the build time of the repo is much, much faster.

Exclude all rocksdbjni targets from build

---

tool/checkstyle/test-coverage.py

We now exclude `target` and `.DS_Store` from checkstyle coverage tests.
`target` is typically a generated folder (e.g. by `cargo`). `.DS_Store` is generated by Finder on a Mac. They should be excluded from checkstyle coverage.
NB: Fixing https://github.com/vaticle/dependencies/issues/253 would remove the need for this PR, but it's harder to do.

Exclude 'target' and '.DS_Store' from checkstyle coverage

---

WORKSPACE
builder/grpc/rust/BUILD
builder/grpc/rust/compile.bzl
builder/grpc/rust/compile.rs

We added the `rust_tonic_compile` rule which compiles `.proto` files into Rust sources that depend on the `tonic` and `prost` crates.
We had an existing Rust binary for compiling proto files into a Tonic library - a Cargo build script in `typedb-protocol`. But Cargo users shouldn't have to run `protoc` on their machine to compile `typedb-client` (which is what happens with a Cargo build script). Rather, the `typedb-protocol` crate should contain the generated Rust gRPC + Protobuf sources.
So we've created a rule, `rust_tonic_compile`, that internally runs a `rust_binary` (similarly to how many of our rules run Kotlin binaries), which uses `tonic_build` to compile `.proto` files into Rust sources, and exposes the outputs. Any `rust_library` can then depend on these generated sources. The …

Add `rust_tonic_compile` rule

---

.gitignore
ide/rust/RepoCargoManifestGenerator.kt
ide/rust/Syncer.kt

The Rust IDE sync tool now generates the correct paths for transitive `@vaticle` dependencies.
Simple explanation:
- Bazel flattens our dependencies and transitive dependencies into a single directory;
- but the `Cargo.toml` we generated behaved as if they were not flattened, but were rather tree-structured. Now, we behave correctly.
More detailed explanation:
Previously, the paths of `@vaticle` dependencies were generated relative to `$(bazel info output_base)` as executed from whatever Bazel workspace the sync tool was currently building. This meant that, for example, if `cloud` depended on `typedb-client-rust` which depended on `typedb-protocol`, we'd generate `bazel-cloud/external/vaticle_typedb_protocol/grpc/rust/Cargo.toml`, but the `Cargo.toml` we generated in `typedb-client-rust` …

IDE sync: generate correct paths for transitive Vaticle deps

---

ide/rust/RepoCargoManifestGenerator.kt
ide/rust/sync_info_aspect.bzl

The Rust IDE sync tool now generates correct paths for crates that contain generated code.
The IDE sync tool had a "sources are generated" flag which triggered when the entry point was generated, but not when other files (like TypeDB Protocol's `typedb.protocol.rs`) were generated. In this PR, we change "sources are generated" to "contains generated sources". When a crate contains generated sources, its generated `Cargo.toml` will now have its entry point set to a location inside `bazel-bin`.
The sync tool builds the project's Rust targets. When a target contains generated sources, Bazel not only places the generated sources in `bazel-bin`, but also creates a symlink in `bazel-bin` for every non-generated source file that links to the source file in the project's working directory. The …

IDE sync: generate correct paths for crates containing generated sources

---

library/crates/BUILD.bazel
library/crates/Cargo.toml

We pin the version of the itertools crate and make it available through bazel.

Add itertools crate to cargo raze

---

ide/rust/RepoCargoManifestGenerator.kt
ide/rust/Syncer.kt
ide/rust/sync_info_aspect.bzl

The Rust IDE sync tool now compiles generated sources in external repositories.
Previously, `typedb-client-rust` would fail to build using `cargo`, because the sources of `typedb-protocol` - imported as an external Bazel repository - were not automatically compiled by the sync tool. So the generated `Cargo.toml` for that target pointed to a valid `lib.rs` file, but that `lib.rs` file depended on `typedb.protocol.rs`, which did not exist, because it had not been created.
Now, whenever the sync tool finds a Bazel Rust target that contains generated sources, it runs `bazel build` on that target to generate those sources.

Rust IDE sync: compile generated sources

---

distribution/deps.bzl

We update to the newest version of bazel-distribution to benefit from https://github.com/vaticle/bazel-distribution/pull/364

Allow longer filenames in crate assembler

---

.gitignore
library/crates/Cargo.lock
library/crates/update.sh

rules_rust's own way of repinning changed dependencies in `crates_repository`, i.e. by setting the `CARGO_BAZEL_REPIN` environment variable to `full` takes a prohibitively long time for minor changes to the cargo manifest. We instead opted for using `cargo generate-lockfile`, which takes an order of magnitude less time to complete (~10 s as opposed to 3-5 minutes).
Using the cargo executable provided by rules_rust seems to be the most correct approach to updating the lockfile. However, calling it directly requires Bazel to build the workspace. Since we have rust executables in dependencies (e.g. `//builder/grpc/rust:compile`), Bazel will attempt to fetch the crates. Fetching the crates will fail if the manifest and the lockfile don't match, which they won't, since we just changed the …

Don't use Bazel in crate-universe lockfile update script

---

distribution/deps.bzl
ide/rust/sync_info_aspect.bzl

`ide/rust:sync` is now more reliable at correctly detecting the crate names of all dependencies. In particular, crates with hyphens (such as `async-trait`) should no longer cause issues.
Crate name detection has been reworked. Because `rules_rust` doesn't expose the original name of the crate downloaded from Cargo anywhere, we were unable to reliably get that crate name and put it into `Cargo.toml`. Now, we use string parsing against the target's label. This works because the label is (e.g):
```
@crates__async-trait-0.36.0//:async_trait
```
We take everything up to + excluding the first `.`, then take everything up to + excluding the last `-`, then strip `@crates__` from the front.
See also:
- https://github.com/vaticle/bazel-distribution/pull/367

Improve crate name detection in Rust IDE sync

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We have added dependencies for the TypeDB Cloud Server to send logs to GCP.
To record tracing logs, we have added Tokio's `tracing` library, and an associated helper library `tracing-subscriber`.

TypeDB Cloud server logging dependencies 

---

builder/java/deps.bzl
distribution/deps.bzl
distribution/helm/deps.bzl

We refactored our dependency on `com_github_masmovil_bazel_rules` (where we get our Helm rules) to depend on a release instead of a commit SHA. 
Recently GitHub was affected by a major incident where commit-based archives changed their SHAs, crippling our whole build infrastructure. `com_github_masmovil_bazel_rules` was one such affected package.
As a precaution, we've upgraded it to the latest version.
We also refactored our dependency on `rules_jvm_external`, which pointed to an outdated (but incidentally still working) GitHub URL format, and updated `bazel-distribution`, which previously depended on `bazel-skylib` by commit SHA.

Avoid depending on commit-based archives

---

distribution/docker/deps.bzl

We downgrade `rules_go` for Apple Silicon compatibility.
See https://github.com/vaticle/typedb/pull/6742 for full explanation.

Downgrade `rules_go` for Apple Silicon compatibility

---

.gitignore
library/crates/Cargo.lock
library/crates/Cargo.toml

We add dependencies used by TypeDB Client Rust for async runtime independence tests.
* `tokio-stream`: utility, maps tokio mpsc channel receivers to streams;
* `http`: remove a layer of indirection;
* `smol` and `async-std`: popular async runtimes.

TypeDB Client Rust dependencies: async runtimes, tokio-stream

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Mixing direct dependencies and those only used for testing purposes can cause confusion about which crates can be safely used as project dependencies. E.g., we wouldn't want a new project to use `async-std` runtime by mistake when everything else uses `tokio`. To alleviate that, we move all dependencies that should only be used in tests into the `[dev-dependencies]` section of Cargo.toml.

Section off cargo dev dependenciess

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add a dependency to the Rust `tower` crate. `tower` is used by `typedb-cloud` for adding advanced configurations to its server.
We add a dependency to `tower 0.4.13`

Add dependency to Tower crate

---

tool/bazelinstall/remote_cache_setup.sh

We now use hyphens in the name of the Bazel cache credential file.
`bazel_cache_credential.json` -> `bazel-cache-credential.json`

Use hyphens in bazel cache credential file name

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We update the cucumber crate in order to be able to use latest API, and add the enum_dispatch crate that is expected to be needed for Concept API.

TypeDB Client Rust dependencies: update cucumber, add enum_dispatch

---

tool/release/notes/Note.kt

We've updated some supporting functions in `Note.kt` to account for the fact that PR goals (i.e. the body of a PR) can be null.
Update function signature and logic of `getPRGoal` to take a nullable String and return a nullable string.

Allow PR body to be null in release notes generation tool

---

builder/antlr/deps.bzl
builder/antlr/rules.bzl

We revert our dependency on a fork of rules_antlr to depend instead on the original repository for the ANTLR code generation rules.
Since we no longer use ANTLR for TypeQL Rust, depending on our own fork of rules_antlr which introduces Rust support is now obsolete.

Remove dependency on forked rules_antlr

---

builder/grpc/deps.bzl
library/maven/artifacts.bzl

We update protobuf from 3.14 to 3.20, along with gRPC definition generation rules, removing reliance on some of our forked dependencies.

Update protobuf & gRPC dependencies

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We increase the version of the `async-stripe` crate to `0.22.2` in order to make use of a new bugfix.
We increase the version of `async-stripe` specified in `Cargo.toml` to `0.22.2` and re-generate the `Cargo.lock` accordingly.

Increase version of async-stripe crate to 0.22.2

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add the maybe-async crate, which is used to conditionally strip `async` from the typedb-client API for FFI purposes, to the crate repository.

Add maybe-async crate dependency

---

builder/swig/java.bzl

We add attributes to the SWIG Java rule that allow specifying extra files that may be included in the interface, and providing extra arguments to the SWIG executable. 
`enable_cxx` is provided as a separate attribute since in addition to providing the `-c++` flag it also affects the files generated by SWIG.

Allow extra SWIG includes and extra args

---

builder/swig/java.bzl

We preserve the relative paths of the SWIG `.i` interface and `.swg` includes, for more general handling of SWIG.

SWIG rules fixes

---

library/maven/artifacts.bzl

Add explicit dependency on jNaCl (a java libsodium port), used for key pair validation in ZeroMQ. 
* Adds jNaCl to `artifacts.bzl`.
(jNaCl is used internally by zeromq, so it has always been a runtime dependency)

Add explicit jNaCl dependency for ZeroMQ key verification

---

builder/rust/cargo/project_aspect.bzl

In Bazel 6.2.0 targets can start with `"@//"`. In `project_aspect.bzl` we have a target name check that is now updated according to this change in bazel.

Fix target label check in the cargo project generation

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add a dependency to the `tokio-retry` crate. It is used by `typedb-cloud` to retry certain API calls.
We add a dependency to `tokio-retry 0.3.0`

Add tokio-retry crate

---

library/maven/artifacts.bzl

We upgrade SpeeDB to 2.6.0, which is marginally faster even without any configuration changes.

Upgrade speedb to 2.6.0

---

distribution/helm/deps.bzl

We upgrade masmovil bazel rules to v0.5.0

Upgrade helm bazel rules

---

library/maven/artifacts.bzl
util/platform/BUILD
util/platform/constraints.bzl

We add skiko linux- and macos-arm64 dependencies.
Drive-by: rename aarch64 platform constraint to arm64.

Add arm64 skiko dependencies for TypeDB-Studio

---

util/platform/BUILD

We remove the stray reference to the non-existence `constraint_win_arm64` rather than the present `constraint_win_x86_64`

Remove stray win_arm64 reference

---

tool/checkstyle/test-coverage.py

The checkstyle coverage check failed if there were files in the workspace with whitespaces in filenames. We fix it.
The list of files was generated by splitting the `find` command result by all whitespace characters. But each file is listed in a separate line, that allows us to split by `"\n"` only.

Fix checkstyle coverage check for filenames with whitespaces

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add the `jsonwebtoken` crate for use in TypeDB Cloud for JWT validation, as `alcoholic_jwt` was insufficient for our purposes due to lacking the ability to validate signatures against an RSA PEM certificate.
We add a dependency to `jsonwebtoken 8.3.0`

Add jsonwebtoken crate

---

builder/cpp/deps.bzl

Add google's GTEST as dependency for use in our C and C++ code in typedb-driver.
* Introduces google's gtest library as a dependency.

Introduce dependencies and rules for C and C++

---

builder/rust/deps.bzl
library/crates/Cargo.lock
library/crates/Cargo.toml

We introduce the `serde_yaml` crate for use in TypeDB Cloud. We also pin the `webpki` crate to prevent build issues that arose from updating it.
We add `serde_yaml = "=0.9.25"` and `webpki = "=0.22.2"` to the `Cargo.toml` and then update the `Cargo.lock` accordingly.

Introduce serde_yaml crate

---

builder/compose/deps.bzl

We replace the "latest" JDK 17 download links with the specific versions from the archive.

Pin JDK 17 versions and URLs

---

builder/rust/deps.bzl
library/crates/crates.bzl

The patch resolves a long-standing issue with incorrect build dependency resolution when a dependency is also a disabled optional normal dependency. See https://github.com/bazelbuild/rules_rust/issues/2059.

Switch to our patched version of rules_rust (based off v0.30.0)

---

builder/grpc/rust/compile.rs

tonic-build gives gRPC methods that return a stream (e.g. `transaction()`) a dedicated type alias for the return type. The name of the type is `{method name}Stream`, which violates Rust naming conventions. We don't have control over those type names though, so the next best thing is disabling the diagnostic altogether.

Disable non-camel-case warnings in tonic compile

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Add env_logger=0.10.0 as a crate dependency for FFI-based driver logging.

Add env_logger crate dependency

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We've enabled the 'tls-roots' on our tonic crate. This means tonic will now trust all of the root certificates in the user's root certificate store when making connections.
Enabled the 'tls-roots' feature flag on the tonic crate.
Drive-by: sort the crates alphabetically.

Enable native TLS roots feature on tonic

---

builder/cpp/deps.bzl
builder/cpp/rules.bzl
library/cpp/.clang-format
library/cpp/BUILD
library/cpp/clang_format.sh

Adds rules & dependencies for building C++ targets.
* Adds dependencies for the C++ typedb-driver
- Gherkin, for parsing gherkin BDD feature files in C++
- Cucumber messages, for the C++ representation of the gherkin language. 
- A json (`nlohmann/json`) library which is in the dependencies for cucumber messages, gherkin & building the C++ driver.
* Adds the `clang_format_test` target type for ensuring C++ style compliance.

Add rules and dependencies for C++ targets

---

library/maven/artifacts.bzl

We update the version of Java com.google.protobuf library to align with the version referred to by the Bazel distribution of io.grpc.

Update protobuf version to align with io.grpc

---

.gitattributes
builder/java/BUILD
builder/java/logback.xml
builder/java/rules.bzl
library/maven/rules.bzl

Move TypeDB test helper rules from typedb-common to dependencies.
The `maven()` rule receives an additional `internal_artifacts` argument so we can depend on internal maven dependencies without pinning them additionally in this repository.

Move typedb_java_test rule to dependencies

---

builder/proto_grpc/rust/compile.bzl

We update the `rust_tonic_compile` bazel rule to refer to `//builder/proto_grpc/rust:compile`, which was moved from `//builder/grpc/rust:compile` in #492

Update target label moved from grpc to proto_grpc

---

tool/release/notes/Commit.kt
tool/release/notes/Note.kt
tool/release/notes/Version.kt

We update the release notes generator tool to be able to handle `-rc1` in a version tag, and to generate the complete change log during a full release since previous full release.
We also only emit a PR description once per PR. Github lists as pulls for a given commit all pull requests involving the commit, which includes e.g. merges from development into master. We now restrict each PR description to only be emitted once, and fallback to the commit message if all PRs have been filtered out.

Release notes generator: RC support and ignore prereleases to generate changelog since previous release

---

builder/rust/rules.bzl

Add OutputGroupInfo to cbindgen rule. This makes it easy to reference the header and document the C driver.
Add OutputGroupInfo to cbindgen rule for easy reference to the header file

Add OutputGroupInfo to cbindgen rule

---

library/maven/artifacts.bzl

We've bumped a dependency on Mailgun Java and added feign-core, which is a dependency required for the operation of the Mailgun client.
As above.

Bump mailgun java dependency

---

library/maven/artifacts.bzl

We need to add "ch.qos.logback.contrib:logback-json-classic | logback-json-core | logback-jackson" for TypeDB Platform to integrate with GCP Structured Logging
As above

Logback-contrib libraries

---

builder/cpp/deps.bzl

Update cucumber BDD dependencies for C++
We depended on our own fork of cucumber-messages & gherkin because we had to add a fix for clang. 
The changes have since made it into the upstream repositories, so we update the dependencies to point back to them.

Update cucumber BDD dependencies for C++

---

builder/cpp/deps.bzl

Update cucumber BDD dependencies for C++
#517 missed updating the dependency to `nlohmann/json`. Though the previous version works fine on a Mac, it does not link on linux. This PR updates the dependency to that expected by cucumber.

Update JSON dependency used by C++ cucumber BDD

---

builder/cpp/deps.bzl

Revert updates to C++ dependencies 
Reverts the changes made in  #522 and #517  since gherkin & cucumber messages seem to be out of sync, causing linux builds to fail.

Revert updates to C++ dependencies

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add the `macro_rules_attribute` crate, which allows us to use a declarative macro in attribute position:
```rs
macro_rules! decorator { /* … */ }
#[apply(decorator)]
struct Foo { /* … */ }
```

Add macro rules attribute crate

---

tool/common/deps.bzl
tool/github/BUILD
tool/github/OpenPR.kt

We've created a tool that can be used to open a PR on GitHub. Now, programatically creating PRs is possible and convenient.
As above.
```
bazel run @vaticle_dependencies//tool/github:open-pr -- \
--repo=vaticle/typedb \
--head-branch=development \
--base-branch=master \
--title="Release" \
--body="Replace me" \
--token=$GITHUB_TOKEN
```
By default, we provide an empty body for the PR and 'vaticle-bot' for the username.

Open PR tool

---

library/maven/artifacts.bzl
tool/sonarcloud/BUILD
tool/sonarcloud/code-analysis.py
tool/sonarcloud/deps.bzl

Introduce JaCoCo dependencies and improve the operation of the sonar code analysis tool
We add the required dependencies, and modify the sonar code analysis tool to:
- use `sonar.token` instead of `sonar.login`
- accept an optional `--coverage-reports` parameter for JaCoCo XML coverage reports
- only download required plugins
- Use the mac and linux platform-specific CLI tool where possible, which comes with a packaged JRE, allowing it to run correctly on machines that don't have the required Java 17

JaCoCo dependencies and Sonar tool improvements

---

library/crates/Cargo.lock
library/crates/Cargo.toml

This crate provides a safe and simple cross platform way to determine whether two file paths refer to the same file or directory, i.e. are hard linked.

Add same-file crate dependency

---

library/maven/artifacts.bzl

Bump our maven dependency on snake-yaml to 2.2
Updates snake-yaml to 2.2. 
TypeDB's ConfigParserTest was confirmed to pass with no changes needed.

Bump snake-yaml maven dependency to 2.2

---

builder/python/deps.bzl
distribution/deps.bzl

Bump rules_python to fix windows error on sync.
rules_python 0.24.0 was breaking with the error: `module 'pkgutil' has no attribute 'ImpImporter'`. This was fixed by version 0.26.0 (?). We bump the dependency further to 0.31.0

Bump rules_python to 0.31.0

---

tool/sync/dependencies.py

We update the bot URL from bot.vaticle.com to bot.typedb.com.

Update sync dependencies to point to bot.typedb.com

---

builder/nodejs/deps.bzl

Bump aspect_rules_ts to v2.4.0.
TypeDB Platform uses TypeScript 5.2.2. This is required because Angular 17 only supports TypeScript above version 5.2. But `aspect_rules_ts` on the old version (1.45) only supports TypeScript up to 5.1.6.
This change may potentially break Bazel builds of the NodeJS driver (untested). This could occur if symbols (e.g. rules) exposed by `aspect_rules_ts` and used by the NodeJS driver have been functionally changed, renamed, or deleted.

Bump aspect_rules_ts to v2.4.0

---

library/maven/artifacts.bzl

We add a [mockito-kotlin](https://mvnrepository.com/artifact/org.mockito.kotlin/mockito-kotlin/3.0.0) dependency suitable for our `Java` version to have more flexible mocks in `Kotlin` tests, including concurrent functions' mocks for `typedb-diagnostics`.
We add a `mockito-kotlin` library dependency.

Add mockito-kotlin dependency

---

library/crates/Cargo.lock
library/crates/Cargo.toml

A lot of NaiveDateTime methods to do with timestamps have been deprecated since 0.4.35, and recommend to convert the naive date time to UTC first. The replacement APIs were only introduced in 0.4.31. In the interest of future-proofing, we upgrade chrono to the latest available version and use the recommended API.

Update chrono to 0.4.38 to avoid depending on deprecated functionality

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add a dependency on the chrono-tz crate, which extends the chrono crate with the full IANA time zone database.

Add dependency on chrono-tz

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Pinned versions of cargo crate dependencies cause resolution errors [when there are two in the same SemVer compatibility range](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility). (Cf. https://github.com/vaticle/typedb-driver/issues/665)
[It is recommended](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-version-requirements) to use the default version specifier for libraries unless absolutely necessary. This PR unpins all currently pinned crates.io dependencies and updates the lockfile to reflect the changes.

Unpin crate dependency versions

---

builder/rust/cargo/project_aspect.bzl
tool/ide/RustManifestSyncer.kt

We now generate a `Cargo.toml` entry per Bazel `rust_test` entry, if that test is a module/crate on its own and not a set of unit tests, that apply for a specific existing crate (eg. using the `crate = ":target"` attribute).
We support the conversion of Bazel Rust integration test targets when there is exactly 1 source file in the `rust_test` target. Otherwise, we expect that the `crate_root` be set to the source file that contains the test targets.
For example:
```
rust_test(
name = "test_abc",
srcs = ["test_abc_v_1.rs, "common/utils.rs"]
)
```
is now considered ambiguous, and must be updated to:
```
rust_test(
name = "test_abc",
crate_root = "test_abc_v_1.rs",
srcs = ["test_abc_v_1.rs, "common/utils.rs"]
)
```
Unrelatedly, we add `resolver = "2"` for into the root `Cargo.toml`, whenever …

Add integration tests to generated Cargo.toml

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add `paste` crate to our Cargo dependencies: https://crates.io/crates/paste. This crate allows us to get more abilities in Rust code generation. 
[Example of usage in TypeDB 3.0](https://github.com/farost/typedb/blob/3.0-thing-commit-time-validation/concept/type_/type_manager/validation/operation_time_validation.rs#L281), where we need to generate multiple intermediate functions inside a single macro to reduce copy-paste and additional macro calls.

Add paste crate to dependencies

---

library/crates/Cargo.lock
library/crates/Cargo.toml

This feature enables compilation for `Tz::from_str_insensitive` in `chrono-tz`, which performs case-insensitive IANA timezone lookup.

Add "case-insensitive" feature to chrono-tz crate

---

distribution/deps.bzl

We add `pip` packages version reformatting from our (TypeDB) version
conventions to [the python
conventions](https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers)
for `alpha` and `beta` releases.
We update the `bazel-distribution` commit to https://github.com/typedb/bazel-distribution/commit/6874e2aac53ba541fc944916dfa5b8f938f33af8

Add reformatting for alphas and betas

---

builder/python/deps.bzl

We update python bazel rules version to [0.37.2](https://github.com/bazelbuild/rules_python/releases) to unlock Python 3.13.
We update python bazel rules version to 0.37.2 to unlock Python 3.13.

Update python bazel rules version to 0.37.2 to unlock Python 3.13

---

builder/rust/cargo/project_aspect.bzl
library/crates/Cargo.lock
library/crates/Cargo.toml
tool/ide/RustManifestSyncer.kt

We add Rust crate dependencies for the TypeDB Server that are used by the newly introduced diagnostics package:
* [hyper](https://crates.io/crates/hyper) - one of the most popular HTTP crates used for working with REST API (creating HTTP clients and servers);
* [hyper-rustls](https://crates.io/crates/hyper-rustls) - TLS (HTTPS) support for `hyper` without dependencies on `openssl`;
* [sysinfo](https://crates.io/crates/sysinfo) - a crate for retrieving information about the system (memory, disks, processes, etc.);
* [xxhash-rust](https://crates.io/crates/xxhash-rust) - an implementation for a hasher with consistent results over all OSs, archs, and server reboots (used for database names hashing).
We modify the `RustManifestSyncer` so it can process source (and compile time) files from a …

Add dependencies used in diagnostics package of the Rust TypeDB server

---

common/java/BUILD
common/java/yaml/YAML.java

Allow setting `snakeyaml.LoaderOptions` when loading YAML
We have run into issues caused by YAML alias count limits that we would like to resolve by modifying that limit - which is done for `snakeyaml` through the `LoaderOptions` object.
We add alternative implementations of `load` that take a `snakeyaml.LoaderOptions` and use it when constructing the `snakeyaml.Yaml` object.

Allow loader options when loading YAML

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Add dependencies for [rust sentry crate](https://crates.io/crates/sentry/0.36.0) to allow sending critical error events from TypeDB Server.
The following dependencies are affected:
* `sentry` is added with the `ureq` feature enabled for events transport serving. The default `reqwest` dependency is not acceptable as it introduces an `openssl` dependency to the server (even if we enable the `rustls` feature), while `ureq` does not require any additional libraries to be set on the host (unlike `curl` which requires `libcurl` installation).
* `ureq` is explicitly added to enable the `tls` feature.
* `async-stripe`'s version is upgraded to eliminate version conflicts in common dependencies with `sentry` (there is an assumption that it's no longer used in our repos and can be freely updated / …

Add dependencies for rust sentry crate

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Add unicase to crate dependencies.
Needed for the `contains` operator on unicode strings.
Added unicode to `Cargo.toml`, ran `update.sh`

Add unicase to crate dependencies.

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Update dependencies prior to release 3.1.0. In details:
* Update dependencies without pinned versions.
* Update the `rocksdb` crate
* Pin the version of the `cc` create to avoid breaking `rocksdb` Bazel build.
Make sure that the dependencies are in a stable and non-conflicting state
See comments.

Update dependencies for 3.1.0

---

tool/ide/RustManifestSyncer.kt

When two library targets with the same crate name and path appear among the bazel rust targets, we assume them to refer to the same crate, but with different configuration (e.g., different set of enabled features).
We were incorrectly using the properties file paths (unique per target) to merge the properties rather than the project paths.

Merge crate properties by path

---

builder/rust/cargo/project_aspect.bzl
tool/ide/RustManifestSyncer.kt

Introduce `declared_features` to the Rust sync tool, parsed from the tags of Bazel `rust_` targets, to generate `Cargo.toml` files with predeclared features that are not automatically used in the dependent targets (this happens with `crate_features`).
We need a way to declare features without their automatic usage to be able to activate them manually through `cargo` only when needed.
Parse `tags` in order to search for a new tag containing a list of declared features. Save these features into a new separate field which is then passed to the crate features declaration.

Add declared crate features to the Rust sync tool

---

library/crates/Cargo.lock
library/crates/Cargo.toml

We add and update dependencies for `axum`-based HTTP server and related crates for encryption and serialization.

Add axum dependencies for TypeDB HTTP endpoint

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Because of numerous build and linking issues with the aws-lc-sys crate, we ensure rustls uses ring rather than (default) asw-lc as its cryptographic provider.

Disable aws-lc-rs in rustls

---

library/crates/Cargo.lock
library/crates/Cargo.toml

Add the latest version of the `base64` crate to the Rust dependencies.
Additionally, pin the `backtrace` to the previous version to support old versions of Rust (its newest version, which is auto-updated in cargo, [requires](https://crates.io/crates/backtrace/versions) Rust 1.82, and it breaks our applications builds).
This crate enables us to encode byte arrays into strings with a total space overhead of ~1.33x, making it useful for transferring TypeDB IIDs over the network when human readability is not required.

Add base64 crate dependency

---

builder/proto_grpc/deps.bzl
builder/proto_grpc/rust/compile.rs

Enable operating systems using Apple Clang 17+ (e.g., MacOS 15.5) to build TypeDB's gRPC dependency by overriding a gRPC's transitive dependency on an older version of `zlib` by the newest version of `zlib`.
It is impossible to build any application using our gRPC dependencies because of a new compilation error related to zlib:
```
external/zlib/BUILD.bazel:32:11: Compiling zutil.c [for tool] failed: (Exit 1): wrapped_clang failed: error executing command (from target @zlib//:zlib) external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 34 arguments skipped)
....
In file included from external/zlib/zutil.c:10:
In file included …
```

Introduce a newer zlib dependency for the gRPC rules

---

tool/github/OpenPR.kt

We fix a bug where our Open GitHub PR tool would log the token passed into it.
Logging tokens is bad.
Previously the token was passed in via a CLI argument. Now it uses an environment variable instead.
----
⚠️ This will require further changes downstream in consumer repos. They will need to set the following environment variable: `OPEN_PR_GITHUB_TOKEN`.

Fix "Open PR" tool logging tokens

---

builder/nodejs/defs.bzl

Add license header to `builder/nodejs/defs.bzl`.

Fix checkstyle build

---

WORKSPACE
builder/rust/versions.bzl

Introduces rust_toolchain_versioned to pin rust version in all downstream toolchains
Have a single function so each repository does not independently set version, supported targets and other toolchain details

Introduces rust_toolchain_versioned to pin rust version in all downstream toolchains
